# Generated by Django 6.0 on 2026-03-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coins',
            field=models.IntegerField(default=1250),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_gift_claim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
